# Generated by Django 4.1.10 on 2023-08-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations2', '0002_relation_metadata'),
        ('apis_ontology', '0004_alter_court_alternative_label_alter_court_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonHasLivingPlace',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_relations2.relation')),
            ],
            bases=('apis_relations2.relation',),
        ),
    ]
