# Generated by Django 4.1.10 on 2023-09-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0004_alter_court_alternative_label_alter_court_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='function',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
