# Generated by Django 4.1.10 on 2023-08-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0005_personhaslivingplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='personhaslivingplace',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personhaslivingplace',
            name='end_date_written',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='personhaslivingplace',
            name='end_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personhaslivingplace',
            name='end_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personhaslivingplace',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personhaslivingplace',
            name='start_date_written',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Start'),
        ),
        migrations.AddField(
            model_name='personhaslivingplace',
            name='start_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personhaslivingplace',
            name='start_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
