# Generated by Django 4.1.10 on 2023-08-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0007_event_eventtookplaceat_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_eventtookplaceat_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event_eventtookplaceat_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event_eventtookplaceat_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event_eventtookplaceat_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event_eventtookplaceat_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event_eventtookplaceat_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionginghervoraus_function',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionginghervoraus_function',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionginghervoraus_function',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionginghervoraus_function',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionginghervoraus_function',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionginghervoraus_function',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionhastietofunction_function',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionhastietofunction_function',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionhastietofunction_function',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionhastietofunction_function',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionhastietofunction_function',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionhastietofunction_function',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionisholdby_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionisholdby_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionisholdby_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionisholdby_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionisholdby_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionisholdby_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_court',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_court',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_court',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_court',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_court',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_court',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_institution',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_institution',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_institution',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_institution',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_institution',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionislocatedatinstitution_institution',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionispossiblypartoffunction_function',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionispossiblypartoffunction_function',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionispossiblypartoffunction_function',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionispossiblypartoffunction_function',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionispossiblypartoffunction_function',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionispossiblypartoffunction_function',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionissubordinaryof_function',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionissubordinaryof_function',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionissubordinaryof_function',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionissubordinaryof_function',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionissubordinaryof_function',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionissubordinaryof_function',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionwaslocatedin_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionwaslocatedin_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionwaslocatedin_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionwaslocatedin_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionwaslocatedin_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_functionwaslocatedin_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctionexecutessalary_salary',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctionexecutessalary_salary',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctionexecutessalary_salary',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctionexecutessalary_salary',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctionexecutessalary_salary',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctionexecutessalary_salary',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctiontakessalary_salary',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctiontakessalary_salary',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctiontakessalary_salary',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctiontakessalary_salary',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctiontakessalary_salary',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function_personorfunctiontakessalary_salary',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionbelongstoinstitution_institution',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionbelongstoinstitution_institution',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionbelongstoinstitution_institution',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionbelongstoinstitution_institution',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionbelongstoinstitution_institution',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionbelongstoinstitution_institution',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutiongiveninmortageto_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutiongiveninmortageto_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutiongiveninmortageto_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutiongiveninmortageto_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutiongiveninmortageto_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutiongiveninmortageto_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionhastietoinstitution_institution',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionhastietoinstitution_institution',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionhastietoinstitution_institution',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionhastietoinstitution_institution',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionhastietoinstitution_institution',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionhastietoinstitution_institution',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionlocatedin_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionlocatedin_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionlocatedin_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionlocatedin_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionlocatedin_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionlocatedin_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionorderssalary_salary',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionorderssalary_salary',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionorderssalary_salary',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionorderssalary_salary',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionorderssalary_salary',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionorderssalary_salary',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionpaidsalary_salary',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionpaidsalary_salary',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionpaidsalary_salary',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionpaidsalary_salary',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionpaidsalary_salary',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution_institutionpaidsalary_salary',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personauthorizedsalary_salary',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personauthorizedsalary_salary',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personauthorizedsalary_salary',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personauthorizedsalary_salary',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personauthorizedsalary_salary',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personauthorizedsalary_salary',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personbornin_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personbornin_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personbornin_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personbornin_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personbornin_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personbornin_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persondiedin_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persondiedin_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persondiedin_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persondiedin_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persondiedin_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persondiedin_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persongetspensionfrominstitution_institution',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persongetspensionfrominstitution_institution',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persongetspensionfrominstitution_institution',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persongetspensionfrominstitution_institution',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persongetspensionfrominstitution_institution',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persongetspensionfrominstitution_institution',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhadbusinessrealtionshipwithperson_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhadbusinessrealtionshipwithperson_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhadbusinessrealtionshipwithperson_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhadbusinessrealtionshipwithperson_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhadbusinessrealtionshipwithperson_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhadbusinessrealtionshipwithperson_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhascorrespondancewith_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhascorrespondancewith_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhascorrespondancewith_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhascorrespondancewith_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhascorrespondancewith_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhascorrespondancewith_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasdisputewith_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasdisputewith_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasdisputewith_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasdisputewith_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasdisputewith_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasdisputewith_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasfamilyrelationwith_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasfamilyrelationwith_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasfamilyrelationwith_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasfamilyrelationwith_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasfamilyrelationwith_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasfamilyrelationwith_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhashometown_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhashometown_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhashometown_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhashometown_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhashometown_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhashometown_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhaslivingplace_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhaslivingplace_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhaslivingplace_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhaslivingplace_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhaslivingplace_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhaslivingplace_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasmarrigewith_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasmarrigewith_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasmarrigewith_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasmarrigewith_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasmarrigewith_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personhasmarrigewith_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisbrotherof_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisbrotherof_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisbrotherof_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisbrotherof_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisbrotherof_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisbrotherof_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personiscustodianofperson_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personiscustodianofperson_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personiscustodianofperson_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personiscustodianofperson_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personiscustodianofperson_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personiscustodianofperson_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisfatherof_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisfatherof_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisfatherof_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisfatherof_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisfatherof_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisfatherof_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisservantofperson_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisservantofperson_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisservantofperson_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisservantofperson_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisservantofperson_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisservantofperson_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personissonof_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personissonof_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personissonof_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personissonof_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personissonof_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personissonof_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisworkinginplace_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisworkinginplace_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisworkinginplace_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisworkinginplace_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisworkinginplace_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personisworkinginplace_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctionexecutessalary_salary',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctionexecutessalary_salary',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctionexecutessalary_salary',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctionexecutessalary_salary',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctionexecutessalary_salary',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctionexecutessalary_salary',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctiontakessalary_salary',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctiontakessalary_salary',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctiontakessalary_salary',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctiontakessalary_salary',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctiontakessalary_salary',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personorfunctiontakessalary_salary',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personownsplace_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personownsplace_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personownsplace_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personownsplace_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personownsplace_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personownsplace_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personplaceofresidence_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personplaceofresidence_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personplaceofresidence_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personplaceofresidence_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personplaceofresidence_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personplaceofresidence_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personpossibleidenticalwithperson_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personpossibleidenticalwithperson_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personpossibleidenticalwithperson_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personpossibleidenticalwithperson_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personpossibleidenticalwithperson_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personpossibleidenticalwithperson_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personrecommendedpersonforcourt_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personrecommendedpersonforcourt_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personrecommendedpersonforcourt_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personrecommendedpersonforcourt_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personrecommendedpersonforcourt_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personrecommendedpersonforcourt_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personsellspropertyto_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personsellspropertyto_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personsellspropertyto_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personsellspropertyto_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personsellspropertyto_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personsellspropertyto_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persontookpartinevent_event',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persontookpartinevent_event',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persontookpartinevent_event',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persontookpartinevent_event',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persontookpartinevent_event',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_persontookpartinevent_event',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personvouchersforperson_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personvouchersforperson_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personvouchersforperson_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personvouchersforperson_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personvouchersforperson_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personvouchersforperson_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasactiveininstitution_institution',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasactiveininstitution_institution',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasactiveininstitution_institution',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasactiveininstitution_institution',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasactiveininstitution_institution',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasactiveininstitution_institution',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasmemberofinstitution_institution',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasmemberofinstitution_institution',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasmemberofinstitution_institution',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasmemberofinstitution_institution',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasmemberofinstitution_institution',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwasmemberofinstitution_institution',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwaspresentatcourt_court',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwaspresentatcourt_court',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwaspresentatcourt_court',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwaspresentatcourt_court',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwaspresentatcourt_court',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_personwaspresentatcourt_court',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='place_placelocatedinplace_place',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='place_placelocatedinplace_place',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='place_placelocatedinplace_place',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='place_placelocatedinplace_place',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='place_placelocatedinplace_place',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='place_placelocatedinplace_place',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_personrecievedsalary_person',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_personrecievedsalary_person',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_personrecievedsalary_person',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_personrecievedsalary_person',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_personrecievedsalary_person',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_personrecievedsalary_person',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salaryorderedby_function',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salaryorderedby_function',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salaryorderedby_function',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salaryorderedby_function',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salaryorderedby_function',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salaryorderedby_function',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salarypaidto_function',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salarypaidto_function',
            name='end_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salarypaidto_function',
            name='end_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salarypaidto_function',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salarypaidto_function',
            name='start_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary_salarypaidto_function',
            name='start_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
